(IRO-2638) Added hash Icon to transaction table.
iron-fish/block-explorer pull request #119
Opened 2022-09-28 12:46 UTC by azhurauski-sc

2022-09-28 18:26 UTC, skylarrichard123 requested changes
https://linear.app/ironfish/issue/IRO-2643/new-requests-feedback-on-pr-httpsgithubcomiron-fishblock

2022-09-29 14:16 UTC, azhurauski-sc commented
@skylarrichard123 please check badge positioning, table header will be fixed a bit later.

2022-09-30 05:06 UTC, ndemidovich-sc commented
@azhurauski-sc Please fix build.

2022-10-04 11:32 UTC, ndemidovich-sc approved these changes

2022-10-04 11:32 UTC, ndemidovich-sc commented on components/TransactionsTable/TransactionsTable.tsx
> +        mx={{ base: '32px', sm1: 0 }}
```suggestion
        mx={{ base: '2rem', sm1: 0 }}
```

2022-10-04 14:00 UTC, skylarrichard123 approved these changes

2022-10-05 09:15 UTC, merged