IRO-2695 - Replaced Fee label with Reward label.
iron-fish/block-explorer pull request #124
Opened 2022-11-01 07:58 UTC by ndemidovich-sc

2022-11-01 19:07 UTC, skylarrichard123 requested changes
there's still a negative sign: https://block-explorer-git-iro-2695-ironfish.vercel.app/transaction/d406e36e5cf71f775df93e37da149764200fb073b4d3b7e74cb0f994ffc51215

2022-11-02 06:52 UTC, ndemidovich-sc commented
> 

Fixed.

2022-11-02 06:52 UTC, ndemidovich-sc commented
Fixed.



> there's still a negative sign: https://block-explorer-git-iro-2695-ironfish.vercel.app/transaction/d406e36e5cf71f775df93e37da149764200fb073b4d3b7e74cb0f994ffc51215

Fixed.

2022-11-02 12:21 UTC, skylarrichard123 approved these changes

2022-11-03 05:20 UTC, merged