IRO-1416: Update eslint rule to align with typescript
iron-fish/block-explorer pull request #61
Opened 2021-12-15 23:56 UTC by yuryironfish

2021-12-16 00:05 UTC, brekk reviewed
Some questions and suggestions. Mainly looking good!

2021-12-16 00:05 UTC, brekk commented on src/components/RefreshButton/RefreshButton.tsx
> +  onClick: unknown
Probably you want something like:
```
  onClick: () => unknown
```
Or if you wanna get serious I think the proper one:
```
  onClick: MouseEventHandler<HTMLButtonElement>
```
And `MouseEventHandler` can be imported from `react`

2021-12-16 00:05 UTC, brekk commented on src/components/RefreshButton/RefreshButton.tsx
> +    if (typeof onClick === 'function') {
Then you won't need to have this condition in play

2021-12-16 00:05 UTC, brekk commented on src/container/BlockDetailPage/BlockDetailPage.tsx
> +            title: Number(t('app.components.breadcrumb.explorer')),
Why is this one a Number but the next one is being cast as a string? Isn't the title always supposed to be a string?

2021-12-16 00:05 UTC, brekk commented on src/container/Explorer/Explorer.tsx
> +    if (typeof resetAndFetch === 'function') {
Pretty sure it's always supposed to be a function

2021-12-16 00:05 UTC, brekk commented on src/types/Transaction.ts
>  }
I updated this file in my PR, might be helpful: https://github.com/iron-fish/block-explorer/blob/308c073a5ca93aea59f1ba88b4671fa6b8e52cd8/src/types/Transaction.ts and it has less defensive checking

2021-12-16 18:15 UTC, leanthebean commented on src/container/TransactionDetailPage/TransactionDetailPage.tsx
> +              title: t('app.components.breadcrumb.explorer') as string,
why not just make all these strings instead of casting them as strings?

2021-12-22 03:08 UTC, dguenther commented
It looks like there was an error building this?

2021-12-23 20:28 UTC, brekk requested changes
Some good changes, but a few places where the component / file is much less usable and a few places that look like outright regressions; are you certain this branch is up to date with the latest `master`?

2021-12-23 20:28 UTC, brekk commented on src/container/BlockDetailPage/BlockDetailPage.tsx
> -  const { sequence, hash, transactions, graffiti, difficulty, timestamp } = blockData
So, structurally, I'm surprised that you removed this block, I think this form is much more readable and the early return makes it so you don't have to constantly re-assert `blockData && <JSX>` down below.

2021-12-23 20:28 UTC, brekk commented on src/container/BlockDetailPage/BlockDetailPage.tsx
> +        <TransactionsList transactions={blockData.transactions} blockHash={blockData.hash} />
Yeah all of this file is more verbose than before, with no upside.

2021-12-23 20:28 UTC, brekk commented on src/types/Block.ts
> +  return typeof x === 'object' && x !== null && 'transactions' in x && !('block' in x)
Minor, but you rarely have to do `x !== null`, you can just do `x && ` (or sometimes `!!x`) at the beginning and because of coercion it will be the same assertion.

2021-12-23 20:28 UTC, brekk commented on src/types/Transaction.ts
>  }
Not sure why you marked this comment thread as resolved. https://github.com/iron-fish/block-explorer/pull/60/files#diff-b547791d1fd0e3f72020cc11ac056213bb4c8ef7ac80d3b8250a8475276a5043R23 is what is currently in `master` and it is better typed there.

2021-12-23 20:28 UTC, brekk commented on yarn.lock
> +  integrity sha512-zaEMRH6xg8ESMi2eQ3R4eZ5qw/hJiVsO/HlLwniIwErij0JDr9P+8V4dtx1l+kLq6j3yy8l8W4fst1lBnat5wQ==
Why is `yarn.lock` changing but `package.json` didn't change?

2021-12-23 20:28 UTC, NullSoldier commented on src/components/CopyElement/CopyElement.tsx
> -  const handleClose = (event: any, reason: any) => {
Why aren't these typed?

2021-12-23 20:29 UTC, NullSoldier commented on src/components/Dashboard/Stat.test.tsx
> +      <Stat priority='low' title='test' icon={''}>
This just fills out a blank icon. Why is this being added here?

2021-12-23 20:47 UTC, brekk commented on .eslintrc.js
> +    '@typescript-eslint/explicit-module-boundary-types': ['off'],
Also why did this one get turned off?

2021-12-23 21:47 UTC, yuryironfish commented on src/components/Dashboard/Stat.test.tsx
> +      <Stat priority='low' title='test' icon={''}>
That auto fix for 
```Property 'icon' is missing in type '{ children: string; priority: "low"; title: string; }' but required in type 'Prop'.ts(2741)```

2021-12-23 21:56 UTC, yuryironfish commented on .eslintrc.js
> +    '@typescript-eslint/explicit-module-boundary-types': ['off'],
Will update this rule later.

2021-12-23 22:18 UTC, yuryironfish commented on src/container/BlockDetailPage/BlockDetailPage.tsx
> -  const { sequence, hash, transactions, graffiti, difficulty, timestamp } = blockData
Sync with master with rebasing, so this changes are came from master

2021-12-23 22:49 UTC, dguenther commented on src/types/Transaction.ts
>  }
Current diff looks okay to me, unless I'm misunderstanding something.

2021-12-23 22:52 UTC, dguenther approved these changes
The current diff seems like an improvement, so I'd be okay merging it. But it looks like there are still several files with comments disabling the `no-explicit-any` eslint rule that you should try to fix up in a future PR.

2021-12-23 23:05 UTC, brekk commented on src/types/Transaction.ts
>  }
Also the return type should definitely be `boolean`, no?

2021-12-23 23:14 UTC, yuryironfish commented on src/components/Meta/Meta.tsx
> +      getTransactionDetailPageUrl(String(variables?.blockHash), String(variables?.hash))
the blocked of removing String is varialbles?.id from line 57

2021-12-23 23:24 UTC, yuryironfish commented on src/types/Transaction.ts
>  }
yes, but it will require additional work to fix other issue if we change  return type to boolean

2021-12-23 23:26 UTC, brekk approved these changes
Sounds like some stuff will be addressed in a future update.

2021-12-23 23:27 UTC, merged

2021-12-23 23:38 UTC, NullSoldier commented on src/types/Transaction.ts
>  }
Return type of bool? You return an assertion for type assertion which then you turn bool in the method.